from pptx import Presentation
from pptx.util import Inches, Pt
import io
import re
import textwrap

def clean_text(text):
    """
    Cleans input text by removing unnecessary special characters and ensuring proper spacing.
    """
    if isinstance(text, list):
        text = "\n".join(text)

    text = re.sub(r'[*#]+', '', text)  # Remove asterisks and hashes
    text = re.sub(r'[^A-Za-z0-9.,\s]', '', text)  # Keep only alphanumeric, spaces, commas, and periods
    text = re.sub(r'\s+', ' ', text).strip()  # Normalize spaces
    return text

def format_text_with_bullets(text):
    """
    Ensures that existing numbered points (1., 2., 3.) are properly formatted with spacing.
    """
    sentences = re.split(r'(?<=[.!?])\s+', text)  # Split by punctuation
    formatted_lines = []

    for sentence in sentences:
        if re.match(r'^\d+\.', sentence.strip()):  # If numbered point
            formatted_lines.append("\n" + sentence.strip())  # Add spacing
        else:
            formatted_lines.append(sentence.strip())  # Keep it as normal text
    
    return formatted_lines

def add_slide(prs, title, content):
    """
    Adds a slide with a title, a properly padded textbox, and formatted bullet points.
    """
    slide_layout = prs.slide_layouts[5]  # Title Only layout
    slide = prs.slides.add_slide(slide_layout)

    # Title Formatting
    title_shape = slide.shapes.title
    title_shape.text = title
    title_shape.text_frame.paragraphs[0].font.bold = True
    title_shape.text_frame.paragraphs[0].font.size = Pt(28)

    # Rectangular Text Box for Content
    textbox = slide.shapes.add_textbox(Inches(0.5), Inches(1.5), Inches(9), Inches(5))
    text_frame = textbox.text_frame
    text_frame.word_wrap = True  
    
    for paragraph in content:
        p = text_frame.add_paragraph()
        p.text = paragraph
        p.font.size = Pt(20)  # Readable font size
        p.space_after = Pt(8)  # Consistent spacing
        
        if re.match(r'^\d+\.', paragraph.strip()):  # If numbered list
            p.level = 0  # Main bullet point
        else:
            p.level = 1  # Sub-point

def create_presentation(title, text):
    """
    Generates a PowerPoint presentation with properly formatted text and bullets.
    """
    prs = Presentation("Ion.pptx")  # Load Ion Theme

    # Title Slide
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = title
    slide.placeholders[1].text = "Generated by AI"

    # Process text and ensure proper formatting
    formatted_text = format_text_with_bullets(text)

    # Add slides with structured bullet points
    max_lines_per_slide = 6  # Prevent overcrowding
    current_slide_text = []

    for line in formatted_text:
        current_slide_text.append(line)

        if len(current_slide_text) >= max_lines_per_slide:
            add_slide(prs, "Key Points", current_slide_text)
            current_slide_text = []

    # Add remaining text
    if current_slide_text:
        add_slide(prs, "Additional Information", current_slide_text)

    # Save presentation to memory
    pptx_io = "/tmp/Generated_Summary_Presentation.pptx"
    prs.save(pptx_io)
    return pptx_io
